# Generated by Django 6.0.5 on 2026-05-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alter_dish_options_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок категории'),
        ),
    ]
