# Generated by Django 6.0.5 on 2026-05-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='dish',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Активно блюдо'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.category', verbose_name='Категория'),
        ),
    ]
