# Generated by Django 6.0.5 on 2026-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_dish_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание блюда'),
        ),
    ]
